# Generated by Django 5.0.2 on 2024-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_folder_slug_alter_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=100)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/')),
                ('booking_date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('expected_number_of_guests', models.PositiveIntegerField()),
                ('budget', models.FloatField(blank=True, default=0.0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('attended', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service', models.ManyToManyField(related_name='service_enquiry', to='core.service')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
